<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBwkaWSS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBwkaWSS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBwkaWSS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBwkaWSS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBwkaWSS\App_KernelDevDebugContainer([
    'container.build_hash' => 'BwkaWSS',
    'container.build_id' => 'e749267a',
    'container.build_time' => 1603191103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBwkaWSS');
