<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPhdESRU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPhdESRU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPhdESRU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPhdESRU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPhdESRU\App_KernelDevDebugContainer([
    'container.build_hash' => 'PhdESRU',
    'container.build_id' => 'fcf04b34',
    'container.build_time' => 1602611583,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPhdESRU');
